### ISSUE TITLE
Inheritance Mapping support

### ISSUE THREAD

**Issue by john-n-smith** [graze/dal#10]
### problem

Dispatch has an abstract class `Stock_Abstract` with concretions `Stock`, `Stock_Case`, `Stock_Layer` and `Stock_Ingredient`. Each concretion has it's own table and unique type id as it's "discriminator".

Throughout Dispatch, these concretions are loaded using `id` and `type`, for example, when retrieving the `Stock_*` record from a `Storage_Rack`

Refactoring this functionality in-line with graze/dal would not currently be possible using mappings alone:

``` yaml
Graze\Dispatch\Entity\StorageRack:
    record: Storage_Rack
    related:
        stock:
            entity: Graze\Dispatch\Entity\Stock || Graze\Dispatch\Entity\StockCase || Graze\Dispatch\Entity\StockLayer ...
            method: getStock
```
### proposal

This functionality requires "class table inheritance", as described [here](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#class-table-inheritance).
Under [Performance Impact](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#id4) they mention multiple JOINs, but this would not be necessary in this example - the correct table can be selected in `related.method` method (the `getStock` method).

The updated YAML could look something like:

```
Graze\Dispatch\Entity\StorageRack:
    record: Storage_Rack
    related:
        stock:
            differentiator: stockTypeId
            entities: 
                1: Graze\Dispatch\Entity\Stock
                3: Graze\Dispatch\Entity\StockCase
                4: Graze\Dispatch\Entity\StockLayer
                differentiatorId: Some\Entity
            method: getStock
```

@wpillar, @adlawson, does this look sensible? Is it something we could implement?
